version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./data/owl.json:/usr/share/nginx/html/owl.json
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  webvowl:
    image: lembutt/webvowl-glossary:latest
    container_name: webvowl
    restart: always
    tty: true
    ports:
      - "33722:8000"
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge